/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.ConfigDat;
import Classes.CreditHistory;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.JOptionPane;

/**
 *
 * @author terra
 */
public class Cobrar extends javax.swing.JDialog {

    /**
     * Creates new form Cobrar
     */
    double result;
    int state;
    String Printer;

    public Cobrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        txtPagoCon.setTransferHandler(null);
        setIconImage(new ConfigDat().getImageIcon().getImage());
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
        result = 0;
        state = 0;
        Printer = "No select";
    }

    public String getPrinter() {
        return Printer;
    }

    public double getResult() {
        return result;
    }

    public int getState() {
        return state;
    }

    public void setData(String[] Data) {
        txtProspect.setText(Data[0]);
        txtTotal.setText(new DecimalFormat("#.00").format(Double.parseDouble(Data[1])));
        txtAbonado.setText(new DecimalFormat("#.00").format(Double.parseDouble(Data[2])));
        txtPendient.setText(new DecimalFormat("#.00").format(Double.parseDouble(Data[3])));
        txtAbonar.requestFocus();
        cargar_impresoras();
    }

    public void cargar_impresoras() {
        combo_printers.removeAllItems();
        PrintService[] ps = PrintServiceLookup.lookupPrintServices(null, null);
        combo_printers.addItem("Imprimir como PDF");
        for (PrintService p : ps) {
            combo_printers.addItem(p.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPagoCon = new javax.swing.JTextField();
        combo_printers = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPendient = new javax.swing.JLabel();
        lbl_cambio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAbonado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtProspect = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAbonar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asistente de pago");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABONAR A CREDITO");

        txtPagoCon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPagoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoConActionPerformed(evt);
            }
        });
        txtPagoCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPagoConKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagoConKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoConKeyTyped(evt);
            }
        });

        combo_printers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combo_printers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imprimir como PDF" }));
        combo_printers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo_printersKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("SU CAMBIO ES:");

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("SE PAGO CON");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("$");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("$");

        txtPendient.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPendient.setText("0.00");

        lbl_cambio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_cambio.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("$");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("SEL. IMPRESORA");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("PROSPECTO");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("MONTO TOTAL");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("ABONADO");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("PENDIENTE");

        txtAbonado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtAbonado.setText("0.00");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("$");

        txtTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTotal.setText("0.00");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("$");

        txtProspect.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtProspect.setText("00000000000");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("SE ABONARA");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("$");

        txtAbonar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAbonarActionPerformed(evt);
            }
        });
        txtAbonar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAbonarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAbonarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAbonarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(combo_printers, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnContinuar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProspect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAbonar)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAbonado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPendient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPagoCon)
                                            .addComponent(lbl_cambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProspect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbonado)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPendient)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(txtAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPagoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_cambio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_printers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnContinuar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagoConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoConKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtPagoCon.getText().contains(".")) {
            evt.consume();
        }
        if (txtPagoCon.getText().equals(".")) {
            txtPagoCon.setText("0.");
        }
    }//GEN-LAST:event_txtPagoConKeyTyped

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        cobrar();
    }//GEN-LAST:event_btnContinuarActionPerformed

    public boolean compCacillas() {
        boolean resp = false;
        if (txtAbonar.getText().equals("")) {
            txtAbonar.requestFocus();
            resp = true;
        } else if (txtPagoCon.getText().equals("")) {
            txtPagoCon.requestFocus();
            resp = true;
        } else if (txtAbonar.getText().equals("") || Double.parseDouble(txtAbonar.getText()) > Double.parseDouble(txtPendient.getText())) {
            txtAbonar.requestFocus();
            resp = true;
        } else if (Double.parseDouble(txtPagoCon.getText()) < Double.parseDouble(txtAbonar.getText())) {
            txtPagoCon.requestFocus();
            resp = true;
        }
        return resp;
    }

    public void cobrar() {
        try {
            if (!compCacillas()) {
                int resp = JOptionPane.showConfirmDialog(null, "Los datos en la compra se guardarán…\n¿seguro que deseas continuar?", "Cancelar", JOptionPane.YES_NO_OPTION);
                if (resp == 0) {
                    asign_datos();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void asign_datos() {
        String nreg = new CreditHistory().genID() + "," + txtProspect.getText() + "," + txtAbonar.getText() + "," + new SimpleDateFormat("dd-MM-YYYY").format(new Date()) + "," + new SimpleDateFormat("HH:MM").format(new Date()) + ",";
        new CreditHistory().InsCredHistRegistry(nreg);
        PrintDoc();
        dispose();
    }

    public void PrintDoc() {
        JOptionPane.showMessageDialog(this, "Falta imprimir documento");
    }

    private void txtPagoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoConActionPerformed
        cobrar();
    }//GEN-LAST:event_txtPagoConActionPerformed

    private void txtPagoConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoConKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            int resp = JOptionPane.showConfirmDialog(null, "¿seguro que deseas cancelar?", "Cancelar", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_txtPagoConKeyPressed

    private void combo_printersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_printersKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            asign_datos();
        }
    }//GEN-LAST:event_combo_printersKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPagoConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoConKeyReleased
        if (!txtPagoCon.getText().replace(" ", "").equals("")) {
            if (txtPagoCon.getText().equals(".")) {
                txtPagoCon.setText("0.");
            }
            if (!txtAbonar.getText().replace(" ", "").equals("") && Double.parseDouble(txtPagoCon.getText()) < Double.parseDouble(txtAbonar.getText())) {
                txtPagoCon.setBackground(Color.RED);
                txtPagoCon.setForeground(Color.WHITE);
            } else {
                txtPagoCon.setBackground(Color.WHITE);
                txtPagoCon.setForeground(Color.BLACK);
            }
            recalc_total();
        } else {
            lbl_cambio.setText(new DecimalFormat("0.00").format(0));
            recalc_total();
        }
    }//GEN-LAST:event_txtPagoConKeyReleased

    private void txtAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbonarActionPerformed
        txtPagoCon.requestFocus();
    }//GEN-LAST:event_txtAbonarActionPerformed

    private void txtAbonarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            int resp = JOptionPane.showConfirmDialog(null, "¿seguro que deseas cancelar?", "Cancelar", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_txtAbonarKeyPressed

    private void txtAbonarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonarKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtAbonar.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAbonarKeyTyped

    private void txtAbonarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonarKeyReleased
        if (!txtAbonar.getText().equals("")) {
            if (txtAbonar.getText().equals(".")) {
                txtAbonar.setText("0.");
            }
            if (Double.parseDouble(txtAbonar.getText()) > Double.parseDouble(txtPendient.getText())) {
                txtAbonar.setBackground(Color.RED);
                txtAbonar.setForeground(Color.WHITE);
            } else {
                txtAbonar.setBackground(Color.WHITE);
                txtAbonar.setForeground(Color.BLACK);
            }
            recalc_total();
        } else {
            lbl_cambio.setText(new DecimalFormat("0.00").format(0));
            recalc_total();
        }
    }//GEN-LAST:event_txtAbonarKeyReleased

    public void recalc_total() {
        try {
            if (!txtPagoCon.getText().equals("")) {
                double total = Double.parseDouble(txtPagoCon.getText()) - Double.parseDouble(txtAbonar.getText());
                lbl_cambio.setText(String.valueOf(new DecimalFormat("0.00").format(total)));
            } else {
                lbl_cambio.setText(new DecimalFormat("0.00").format(0));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cobrar dialog = new Cobrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> combo_printers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_cambio;
    private javax.swing.JLabel txtAbonado;
    private javax.swing.JTextField txtAbonar;
    private javax.swing.JTextField txtPagoCon;
    private javax.swing.JLabel txtPendient;
    private javax.swing.JLabel txtProspect;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
