/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.Encryptor;
import Controllers.userController;
import Models.User;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.ToolTipManager;

/**
 *
 * @author ATENEA
 */
public class newUser extends javax.swing.JDialog {

    /**
     * Creates new form newUser
     */
    userController allUsers = userController.getInstance();
    ToolTipManager ttm = ToolTipManager.sharedInstance();
    User User;
    int continuar = 0;

    public int getContinuar() {
        return continuar;
    }

    public void setContinuar(int continuar) {
        this.continuar = continuar;
    }

    boolean ok = false;

    public boolean isOk() {
        return ok;
    }

    public newUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ttm.setInitialDelay(0);
        ttm.setDismissDelay(10000);
    }

    public void createUser() {
        btnUpdate.setVisible(false);
        User = new User();
        User.setId(allUsers.genID());
        txt_id.setText(User.getId()+"");
    }

    public void editUser(User User) {
        this.User = User;
        btnCreate.setVisible(false);
        txt_id.setText(User.getId()+"");
        txtUsername.setText(User.getUsername());
        txtPassword.setText(User.getPassword());
        cmbRole.setSelectedItem(User.getRole());
    }

    public void setDatFirstUse() {
        jLabel1.setText("CREAR CUENTA ADMIN");
        createUser();
        cmbRole.setSelectedItem("Administrador");
        cmbRole.enable(false);
        this.setDefaultCloseOperation(0);
        txtUsername.setText("admin");
        txtPassword.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Datos de cuenta: ");

        btnCreate.setText("CONTINUAR");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Contraseña");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR CUENTA NUEVA");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Puesto");

        txt_id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_id.setText("000000000000");

        cmbRole.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Administrador" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Rep. Cont");

        txtConfirmPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });
        txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Identificador");

        txtUsername.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsername))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword)
                                    .addComponent(txtConfirmPassword)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_id)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        storeUser();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        txtConfirmPassword.requestFocus();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        String cadena = (txtPassword.getText()).toUpperCase();
        txtPassword.setText(cadena);
        if (txtPassword.getText().isEmpty()) {
            txtPassword.setBackground(txtUsername.getBackground());
            txtPassword.setForeground(txtUsername.getForeground());
        } else {
            if (txtPassword.getText().length() <= 3) {
                txtPassword.setBackground(Color.red);
                txtPassword.setForeground(Color.white);
            } else if (txtPassword.getText().length() > 3 && txtPassword.getText().length() < 6) {
                txtPassword.setBackground(Color.yellow);
                txtPassword.setForeground(Color.black);
            } else {
                txtPassword.setBackground(txtUsername.getBackground());
                txtPassword.setForeground(txtUsername.getForeground());
            }
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    public void updateUser() {
        try {
            if (checkFieldsUpdate()) {
                User.setUsername(txtUsername.getText().replace(',', ' '));
                User.setPassword(txtPassword.getText().replace(',', ' '));
                User.setRole(cmbRole.getSelectedItem().toString());
                User.setEdited();
                if (allUsers.updateUser(User)) {
                    JOptionPane.showMessageDialog(null, "<html><h1>CUENTA ACTUALIZADA CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar</font></html>", "Terminado", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean checkFieldsUpdate() {
        boolean resp = false;
        if (txtUsername.getText().length() > 0) {
            if (txtPassword.getText().length() > 0) {
                if (txtConfirmPassword.getText().length() > 0) {
//                    if (allUsers.findUserByName(txtUsername.getText().replace(',', ' ')) != null) {
                        if (txtPassword.getText().equals(txtConfirmPassword.getText())) {
                            resp = true;
                        } else {
                            txtConfirmPassword.setText("");
                            txtConfirmPassword.requestFocus();
                        }
//                    } else {
//                        JOptionPane.showMessageDialog(this, "<html><h1>ESTE USUARIO NO EXISTE!</h1><font SIZE=5><p>El usuario " + txtUsername.getText().replace(',', ' ') + " ya esta registrado... vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
//                        txtUsername.requestFocus();
//                    }
                } else {
                    txtConfirmPassword.requestFocus();
                }
            } else {
                txtPassword.requestFocus();
//                JOptionPane.showMessageDialog(null, "<html><h1>¡Cuidado faltan datos!</h1><font SIZE=5><p>Falta escribir la contraseña, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            txtUsername.requestFocus();
//            JOptionPane.showMessageDialog(null, "<html><h1>¡Cuidado faltan datos!</h1><font SIZE=5><p>Falta escribir el nombre del usuario, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        }
        return resp;
    }

    public boolean checkFields() {
        boolean resp = false;
        if (txtUsername.getText().length() > 0) {
            if (txtPassword.getText().length() > 0) {
                if (txtConfirmPassword.getText().length() > 0) {
                    if (allUsers.findUserByName(txtUsername.getText().replace(',', ' ')) == null) {
                        if (txtPassword.getText().equals(txtConfirmPassword.getText())) {
                            resp = true;
                        } else {
                            txtConfirmPassword.setText("");
                            txtConfirmPassword.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "<html><h1>ESTE USUARIO YA EXISTE!</h1><font SIZE=5><p>El usuario " + txtUsername.getText().replace(',', ' ') + " ya esta registrado... vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
                        txtUsername.requestFocus();
                    }
                } else {
                    txtConfirmPassword.requestFocus();
                }
            } else {
                txtPassword.requestFocus();
//                JOptionPane.showMessageDialog(null, "<html><h1>¡Cuidado faltan datos!</h1><font SIZE=5><p>Falta escribir la contraseña, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            txtUsername.requestFocus();
//            JOptionPane.showMessageDialog(null, "<html><h1>¡Cuidado faltan datos!</h1><font SIZE=5><p>Falta escribir el nombre del usuario, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        }
        return resp;
    }

    public void storeUser() {
        if (checkFields()) {
            int dialogButton = JOptionPane.showConfirmDialog(null, "<html><h1>¿CREAR CUENTA?  </h1><font SIZE=5><p> Verifique bien sus datos antes de continuar…</font></html>", "CREAR NUEVA CUENTA", JOptionPane.OK_CANCEL_OPTION);
            if (dialogButton == JOptionPane.OK_OPTION) {                
                User.setUsername(new Encryptor().clearText(txtUsername.getText().replace(',', ' ')));
                User.setPassword(txtPassword.getText().replace(',', ' '));
                User.setRole(cmbRole.getSelectedItem().toString());
                if (allUsers.createUser(User)) {
                    ok = true;
                    JOptionPane.showMessageDialog(null, "<html><h1>CUENTA CREADA CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar</font></html>", "Terminado", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }
        }
    }

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        if (txtPassword.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        storeUser();
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void txtConfirmPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyReleased
        String cadena = (txtConfirmPassword.getText()).toUpperCase();
        txtConfirmPassword.setText(cadena);
        if (txtConfirmPassword.getText().isEmpty()) {
            txtConfirmPassword.setBackground(txtUsername.getBackground());
            txtConfirmPassword.setForeground(txtUsername.getForeground());
        } else {
            if (!txtConfirmPassword.getText().equals(txtPassword.getText())) {
                txtConfirmPassword.setBackground(Color.red);
                txtConfirmPassword.setForeground(Color.white);
            } else {
                txtConfirmPassword.setBackground(txtUsername.getBackground());
                txtConfirmPassword.setForeground(txtUsername.getForeground());
            }
        }
    }//GEN-LAST:event_txtConfirmPasswordKeyReleased

    private void txtConfirmPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyTyped
        if (txtConfirmPassword.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txtConfirmPasswordKeyTyped

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        txtPassword.requestFocus();
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setContinuar(2);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateUser();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                newUser dialog = new newUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel txt_id;
    // End of variables declaration//GEN-END:variables
}
