/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.Cobradores;
import Classes.RouteMapping;
import Classes.Rutas;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author OSBAL
 */
public class RouteMappingD extends javax.swing.JDialog {

    /**
     * Creates new form RouteMappingD
     */
    List<String> Rutas = new ArrayList<>();
    DefaultListModel lm1;

    public RouteMappingD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lm1 = new DefaultListModel();
        listRutas.setModel(lm1);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        btnCerrar.requestFocus();
    }

    public void setNewRegData() {
        lblID.setText(new RouteMapping().genID());
        btnBorrar.setVisible(false);
        loadCobradores();
        loadRutas();
        updateShowText();
    }

    public void setUpdateData(String id) {
        btnAceptar.setVisible(false);
        btnAddRoute.setVisible(false);
        btnDelSelect.setVisible(false);
        cmbCobradores.setEnabled(false);
        cmbRutas.setEnabled(false);
        txtCollector.setEnabled(false);
        txtRuta.setEnabled(false);
        loadCobradores();
//        loadRutas();
        String[] reg = new RouteMapping().getRouteMappingbyID(id);
        lblID.setText(reg[0]);
        cmbCobradores.setSelectedItem(reg[1]);
        loadRutasMapeo(id);
        updateShowText();
        revalidate();
        repaint();
    }

    public void loadRutasMapeo(String id) {
        List database = new RouteMapping().getRouteMapBbyIDRouteMaping(id);
        if (database.isEmpty()) {
            Rutas.add("SIN RUTAS GUARDADAS");
        } else {
            for (int i = 0; i < database.size(); i++) {
                String[] reg = database.get(i).toString().split(",");
                Rutas.add(reg[1]);
            }
        }
    }

    public void updateShowText() {
        getListRutas();
    }

    public void getListRutas() {
        lm1.removeAllElements();
        if (!Rutas.isEmpty()) {
            for (int i = 0; i < Rutas.size(); i++) {
                lm1.addElement(Rutas.get(i));
            }
        }
    }

    public void loadRutas() {
        cmbRutas.removeAllItems();
        List RUTAS = new Rutas().loadRutas();
        if (RUTAS.isEmpty()) {
            cmbRutas.addItem("SIN RUTAS");
        } else {
            for (int i = 0; i < RUTAS.size(); i++) {
                cmbRutas.addItem(RUTAS.get(i).toString());
            }
        }
    }

    public void loadCobradores() {
        cmbCobradores.removeAllItems();
        List RUTAS = new Cobradores().loadCollectors();
        if (RUTAS.isEmpty()) {
            cmbCobradores.addItem("SIN COBRADORES");
        } else {
            for (int i = 0; i < RUTAS.size(); i++) {
                cmbCobradores.addItem(RUTAS.get(i).toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listRutas = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnDelSelect = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbCobradores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCollector = new javax.swing.JTextArea();
        cmbRutas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRuta = new javax.swing.JTextArea();
        btnAddRoute = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crea nuevo Mapeo de ruta");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Mapeo"));

        listRutas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listRutas);

        jLabel4.setText("Lista de rutas");

        btnDelSelect.setText("BORRAR SELEC");
        btnDelSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelSelect)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnDelSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        btnCerrar.setText("CANCELAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAceptar.setText("GUARDAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton4.setText("IMPRIMIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        pnlData.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Basicos"));

        jLabel2.setText("Seleccione Cobrador");

        cmbCobradores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCobradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCobradoresActionPerformed(evt);
            }
        });

        txtCollector.setEditable(false);
        txtCollector.setColumns(20);
        txtCollector.setLineWrap(true);
        txtCollector.setRows(5);
        jScrollPane1.setViewportView(txtCollector);

        cmbRutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRutasActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccionar Ruta");

        txtRuta.setEditable(false);
        txtRuta.setColumns(20);
        txtRuta.setLineWrap(true);
        txtRuta.setRows(5);
        jScrollPane2.setViewportView(txtRuta);

        btnAddRoute.setText("Añadir");
        btnAddRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRouteActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setText("00000000000");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ID Mapeo");

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDataLayout.createSequentialGroup()
                        .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCobradores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDataLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlDataLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlDataLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(104, 104, 104))
                                    .addGroup(pnlDataLayout.createSequentialGroup()
                                        .addComponent(cmbRutas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddRoute))))))
                    .addGroup(pnlDataLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblID)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblID))
                .addGap(10, 10, 10)
                .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDataLayout.createSequentialGroup()
                        .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCobradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDataLayout.createSequentialGroup()
                        .addGroup(pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddRoute))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAceptar)
                    .addComponent(jButton4)
                    .addComponent(btnBorrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRutasActionPerformed
        if (cmbRutas.getItemCount() > 0) {
            cmbActionPreformed(cmbRutas.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbRutasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cmbCobradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCobradoresActionPerformed
        if (cmbCobradores.getItemCount() > 0) {
            cmbActionPreformed2(cmbCobradores.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbCobradoresActionPerformed

    private void btnAddRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRouteActionPerformed
        addRoute();
    }//GEN-LAST:event_btnAddRouteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.out.println("Falta imprimir");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnDelSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSelectActionPerformed
        removeRoute();
    }//GEN-LAST:event_btnDelSelectActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        Delete();
    }//GEN-LAST:event_btnBorrarActionPerformed

    public void Delete() {
        Confirm c = new Confirm(null, true);
        c.setVisible(true);
        if (c.getResp() == 1) {
            if (new RouteMapping().delRouteMapping(lblID.getText())) {
                JOptionPane.showMessageDialog(null, "<html><h1>REGISTRO ELIMINADO CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar</font></html>", "REGISTRO ELIMINADO", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        } else if (c.getResp() == 0) {
            JOptionPane.showMessageDialog(null, "<html><h1>¡ACCESO DENEGADO!</h1><font SIZE=5><p>Verifique sus credenciales...</font></html>", "¡Atencion!", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void Guardar() {
        if (!compCacillas()) {
            String nreg = lblID.getText() + ","
                    + cmbCobradores.getSelectedItem().toString() + ","
                    + new SimpleDateFormat("dd-MM-YYYY").format(new Date()) + ","
                    + new SimpleDateFormat("HH:MM").format(new Date()) + ",";
            if (btnAceptar.getText().equals("GUARDAR")) {
                try {
                    int DB = JOptionPane.showConfirmDialog(null, "<html><h1>AÑADIR NUEVO MAPEO DE RUTAS</h1><font SIZE=5><p> Desea crear un nuevo Registro?</font></html>", "NUEVO REGISTRO", JOptionPane.YES_NO_OPTION);
                    if (DB == 0) {
                        new RouteMapping().insRouteMapping(nreg);
                        saveListRoutes();
                        JOptionPane.showMessageDialog(null, "<html><h1>REGISTRO GUARDADO CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar...</font></html>", "REGISTRO GUARDADO", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e);
                }
            } else {
                try {
                    int dialogButton = JOptionPane.showConfirmDialog(null, "Desea actualizar este Cliente?", "ACTUALIZAR CLIENTE", JOptionPane.YES_NO_OPTION);
                    if (dialogButton == 0) {
//                        new RouteMapping().updateCollector(nreg);
                        JOptionPane.showMessageDialog(this, "Cliente actualizado Correctamente");
                        this.dispose();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e);
                }
            }
        }
    }

    public void saveListRoutes() {
        List<String> save = new ArrayList<>();
        for (int i = 0; i < Rutas.size(); i++) {
            String nreg = new RouteMapping().genIDB() + ","
                    + Rutas.get(i) + ","
                    + lblID.getText() + ",";
            new RouteMapping().insRouteMappingB(nreg);
        }
    }

    public boolean compCacillas() {
        boolean resp = false;
        if ("SIN COBRADORES".equals(cmbCobradores.getSelectedItem().toString())) {
            cmbCobradores.requestFocus();
            resp = true;
        }

        if (lm1.getSize() == 0) {
            cmbRutas.requestFocus();
            resp = true;
        }
        return resp;
    }

    public void removeRoute() {
        String idRuta = listRutas.getSelectedValue();
        if (Rutas.contains(idRuta)) {
            Rutas.remove(idRuta);
        }
        updateShowText();
    }

    public void addRoute() {
        String idRuta = cmbRutas.getSelectedItem().toString();
        if (!Rutas.contains(idRuta) && !"SIN RUTAS".equals(idRuta)) {
            Rutas.add(idRuta);
        }
        updateShowText();
    }

    public void cmbActionPreformed2(String Item) {
        txtCollector.setText(new Cobradores().getCollectorToString(Item));
        txtCollector.setCaretPosition(0);
        updateShowText();
    }

    public void cmbActionPreformed(String Item) {
        txtRuta.setText(new Rutas().getRutaToString(Item));
        txtRuta.setCaretPosition(0);
        updateShowText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RouteMappingD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RouteMappingD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RouteMappingD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RouteMappingD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RouteMappingD dialog = new RouteMappingD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAddRoute;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDelSelect;
    private javax.swing.JComboBox<String> cmbCobradores;
    private javax.swing.JComboBox<String> cmbRutas;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblID;
    private javax.swing.JList<String> listRutas;
    private javax.swing.JPanel pnlData;
    private javax.swing.JTextArea txtCollector;
    private javax.swing.JTextArea txtRuta;
    // End of variables declaration//GEN-END:variables
}
