/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.clientController;
import Classes.CreditHistory;
import Classes.Prospects;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Viernes
 */
public class WCHClient extends javax.swing.JDialog {

    /**
     * Creates new form WCHClient
     */
    DefaultTableModel modelo;

    public WCHClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        btnCerrar.requestFocus();
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                if (columnas < 0) {
                    return true;
                } else {
                    return false;
                }
            }
        };
        modelo.addColumn("ID Registro");
        modelo.addColumn("ID Prospecto");
        modelo.addColumn("Monto abonado");
        modelo.addColumn("Fecha abono");
        modelo.addColumn("Hora abono");
        tableCH.setModel(modelo);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCH = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnAbonar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIdClient = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdCredit = new javax.swing.JTextField();
        txtCredit = new javax.swing.JTextField();
        txtInterestes = new javax.swing.JTextField();
        txtAbonado = new javax.swing.JTextField();
        txtRest = new javax.swing.JTextField();
        lblFinalDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFirstDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial Crediticio Cliente");

        jLabel2.setText("ID Cliente");

        jLabel3.setText("Nombre Cliente");

        jLabel4.setText("Prestamo");

        jLabel5.setText("Fecha Limite de Pago");

        jLabel6.setText("Status");

        jLabel7.setText("Abonado");

        jLabel8.setText("Restante");

        tableCH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCH);

        jLabel9.setText("Ultimos abonos");

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAbonar.setText("ABONAR");
        btnAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarActionPerformed(evt);
            }
        });

        jButton3.setText(" IMPRIMIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Intereses");

        txtIdClient.setEditable(false);

        txtClientName.setEditable(false);

        lblState.setText("ESTATUS");

        jLabel12.setText("ID Credito");

        txtIdCredit.setEditable(false);

        txtCredit.setEditable(false);

        txtInterestes.setEditable(false);

        txtAbonado.setEditable(false);

        txtRest.setEditable(false);

        lblFinalDate.setText("dd-MM-YYYY");

        jLabel14.setText("Fecha Prestamo");

        lblFirstDate.setText("dd-MM-YYYY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbonar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblState))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtInterestes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRest, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblFirstDate))
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblFinalDate))
                                    .addComponent(jLabel5))))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInterestes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFirstDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFinalDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAbonar)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarActionPerformed
        String datos = txtIdCredit.getText() + ","
                + calcTotal(txtCredit.getText(), txtInterestes.getText()) + ","
                //                +txtInterestes.getText()+","
                + txtAbonado.getText() + ","
                + txtRest.getText() + ",";
        Cobrar aac = new Cobrar(null, true);
        aac.setData(datos.split(","));
        aac.show();
        setData(txtIdCredit.getText());
        if (txtRest.getText().equals("0.00")) {
            new Prospects().FinishProspect(txtIdCredit.getText());
        }
    }//GEN-LAST:event_btnAbonarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PrintDoc();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void PrintDoc() {
        JOptionPane.showMessageDialog(this, "Falta imprimir documento");
    }

    public String calcTotal(String dat1, String dat2) {
        String resp = "";
        resp = Double.parseDouble(dat1) + Double.parseDouble(dat2) + "";
        return resp;
    }

    public void setData(String idProspect) {
        String[] registro = new Prospects().getProspectByID(idProspect);
        String[] cliente = new clientController().getClientbyID(registro[1]);
        loadCreditHistory(registro[0]);
        txtIdCredit.setText(registro[0]);
        txtIdClient.setText(cliente[0]);
        txtClientName.setText(cliente[1] + " " + cliente[2]);
        txtCredit.setText(new DecimalFormat("#.00").format(Double.parseDouble(registro[3])));
        txtInterestes.setText(calcIntereses(idProspect));
        txtAbonado.setText(calcAbonado());
        txtRest.setText(calcRestante(txtCredit.getText(), txtInterestes.getText(), txtAbonado.getText()));
        lblState.setText(calcEstado(registro[9]));
        String[] dat = registro[9].split(" --> ");
        lblFirstDate.setText(dat[0]);
        lblFinalDate.setText(registro[7]);
        if (txtRest.getText().equals("0.00")) {
            btnAbonar.setVisible(false);
        }
    }

    public String calcIntereses(String idProspect) {
        String resp = "";
        try {
            String[] registro = new Prospects().getProspectByID(idProspect);
            String[] dat = registro[9].split(" --> ");
            String fechaF1 = dat[0];
            String fechaF2 = new SimpleDateFormat("dd-MM-YYYY").format(new Date());

            String[] date = fechaF1.split("-");
            Date fecha1 = new Date();
            fecha1.setDate(Integer.parseInt(date[0]));
            fecha1.setMonth(Integer.parseInt(date[1]) - 1);
            fecha1.setYear(Integer.parseInt(date[2]) - 1900);

            String[] date2 = fechaF2.split("-");
            Date fecha2 = new Date();
            fecha2.setDate(Integer.parseInt(date2[0]));
            fecha2.setMonth(Integer.parseInt(date2[1]) - 1);
            fecha2.setYear(Integer.parseInt(date2[2]) - 1900);

            if (fecha1.equals(fecha2)) {
                resp = new DecimalFormat("#.00").format(Double.parseDouble(registro[4]));
            } else if (fecha1.after(fecha2)) {
                resp = new DecimalFormat("#.00").format(Double.parseDouble(registro[4]));
            } else if (fecha1.before(fecha2)) {
                resp = new DecimalFormat("#.00").format(Double.parseDouble(registro[5]));
            }

        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
        return resp;
    }

    public String calcAbonado() {
        double total = 0;
        String resp = "0.00";
        try {
            if (tableCH.getRowCount() > 0) {
                for (int i = 0; i < tableCH.getRowCount(); i++) {
                    double monto = Double.parseDouble(tableCH.getValueAt(i, 2).toString());
                    total += monto;
                }
                resp = new DecimalFormat("#.00").format(total);
            } else {
                resp = "0.00";
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
        return resp;
    }

    public String calcRestante(String monto, String intrs, String abonado) {
        double Monto = Double.parseDouble(monto);
        double Intereses = Double.parseDouble(intrs);
        double Abonado = Double.parseDouble(abonado);
        double total = (Monto + Intereses) - Abonado;
        if (total > 0) {
            return new DecimalFormat("#.00").format(total);
        } else {
            return "0.00";
        }
    }

    public String calcEstado(String fecha) {
        String resp = "";
        try {
            String[] dat = fecha.split(" --> ");
            String fechaF1 = dat[0];
            String fechaF2 = new SimpleDateFormat("dd-MM-YYYY").format(new Date());

            String[] date = fechaF1.split("-");
            Date fecha1 = new Date();
            fecha1.setDate(Integer.parseInt(date[0]));
            fecha1.setMonth(Integer.parseInt(date[1]) - 1);
            fecha1.setYear(Integer.parseInt(date[2]) - 1900);

            String[] date2 = fechaF2.split("-");
            Date fecha2 = new Date();
            fecha2.setDate(Integer.parseInt(date2[0]));
            fecha2.setMonth(Integer.parseInt(date2[1]) - 1);
            fecha2.setYear(Integer.parseInt(date2[2]) - 1900);

            if (fecha1.equals(fecha2)) {
                resp = "HOY ES FECHA LIMITE";
            } else if (fecha1.after(fecha2)) {
                resp = "FECHA LIMITE PASADA";
            } else if (fecha1.before(fecha2)) {
                resp = "AUN A TIEMPO";
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
        return resp;
    }

    public void loadCreditHistory(String idProspect) {
        modelo.setRowCount(0);
        List CH = new CreditHistory().getCreditHistoryForProspect(idProspect);
        if (CH != null) {
            for (int i = 0; i < CH.size(); i++) {
                modelo.addRow(CH.get(i).toString().split(","));
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WCHClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WCHClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WCHClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WCHClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WCHClient dialog = new WCHClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFinalDate;
    private javax.swing.JLabel lblFirstDate;
    private javax.swing.JLabel lblState;
    private javax.swing.JTable tableCH;
    private javax.swing.JTextField txtAbonado;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtIdClient;
    private javax.swing.JTextField txtIdCredit;
    private javax.swing.JTextField txtInterestes;
    private javax.swing.JTextField txtRest;
    // End of variables declaration//GEN-END:variables
}
